// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authenticate": {
            "post": {
                "description": "It will authenticate an user from provided information",
                "consumes": [
                    "application/json"
                ],
                "summary": "Authenticate an user",
                "operationId": "authenticate-user",
                "parameters": [
                    {
                        "description": "Username of the user",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Password of the user",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The authentication is complete and access token provided in http only cookies",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "210": {
                        "description": "Wrong authentication information provided",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/authorize": {
            "get": {
                "description": "It will authorize an user with jwt token from http only cookies",
                "consumes": [
                    "application/json"
                ],
                "summary": "Authorize an user",
                "operationId": "authorize-user",
                "responses": {
                    "200": {
                        "description": "The user is authorized",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "210": {
                        "description": "Wrong jwt token",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "It will register an user with provided information",
                "consumes": [
                    "application/json"
                ],
                "summary": "Register an user",
                "operationId": "register-user",
                "parameters": [
                    {
                        "description": "Username of the user",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Password of the user",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The registration is completed",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "210": {
                        "description": "The user is already registered",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
